import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import NavBar from "@/components/NavBar";
import BottomBar from "@/components/BottomBar";
export const metadata: Metadata = {
  title: "MetaBox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <NavBar />
        <div className="container m-auto h-[100vh] overflow-y-scroll my-[65px] ">
          {children}
        </div>
        <BottomBar />
      </body>
    </html>
  );
}
